### PR TITLE
Adding privacy village logo to Bluelog Live header

### PR DESCRIPTION
**Pull request by tbrooks007**
Not sure if this is what you were looking for, but this is what came up with.

### CODE REVIEW

**Comment by MS3FGX** [comment]
Very cool that you've come up with a customized version, and I'm all for including it, but I can't merge this as-is since it would break all the other themes as the HTML itself is modified. To retain compatibility with the other themes, all the customizations have to be within the individual CSS file, and a symlink created to "style.css" rather than hardcoding it into index.html.

If I'm looking at this correctly, it seems like the only real change to the HTML is adding the <H1> "Privacy Village Bluetooth Scanner" line. I would suggest that instead of putting that in the HTML, that a new banner image be created that has your logo and that line of text in it (as a benefit, it can look like whatever you want and doesn't need to rely on system/browser fonts or anything since it will be an image). You can then point to that image with "background-image: url" on line 29 in your CSS, which will put it as the background image in the header. I don't know if you are intentionally including the stock "Bluelog Live" banner image or not, but you certainly don't have to if you don't want to.

Also, instead of hardcoding the privacy_village.css file, you would just symlink it to "style.css" so all you need to do to switch themes is change what the symlink points too. This can also be part of the Makefile, so that a different theme can be set as the default when you do "make install".

**Comment by tbrooks007** [comment]
Ahhh, thanks! I did this in a bit of a rush and completely missed the boat on the index file being a template and the style.css being changed via a symlink under the covers (doh). I will correct this tonight.

**Comment by tbrooks007** [comment]
Updated the index.html to return it to it's original state, updated the privacy village css to include the logo and text.

**Comment by MS3FGX** [comment]
HTML and CSS look good now, but the "privacy_village_banner.png" image isn't in the commit. I'm guessing it is not the same as the original image, so I'll hold off on merge until you get a chance to add it.

Incidentally I have been meaning to add a section to the docs about the "right way" (it's all a bit of a hack anyway...) to do a theme, so I appreciate you having the patience to go through this bit of trial and error essentially blind. I'll make sure to get the docs updated soon with this info so it's a smoother operation in the future should anyone else want to merge in a theme.

**Comment by tbrooks007** [comment]
Hi, doh sorry about that. Added the image now. I also sent all the needed files to Render already (which included the image) so he could use this this weekend.

**Comment by MS3FGX** [comment]
Cool, looks like the file needs to get moved into /images, but I get the point. I'll merge this now, thanks!

**Comment by tbrooks007** [comment]
Cool, thanks for correcting that!

**Pull request merged**
